export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';